media:
  - name: article_images
    label: Article images
    input: src/content/news/images
    output: images
    rename: safe
    extensions: [jpg, jpeg, png, webp]
  - name: author_images
    label: Author images
    input: src/content/authors/images
    output: images
    rename: safe
    extensions: [jpg, jpeg, png, webp]
content:
  - name: articles
    label: Articles
    type: collection
    path: src/content/news
    filename: '{primary}.md'
    subfolders: false
    view:
      primary: title
      fields: [cover, title, date, draft, category]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        description: Used for link previews/search results.
        required: true
        pattern: { message: 'No line breaks allowed', regex: '^[^\r\n]*$' }
      - name: date
        label: Date
        type: date
        required: true
      - name: category
        label: Category
        type: select
        required: false
        options:
          creatable: false
          multiple: false
          values:
            - value: case-study
              label: Case study
            - value: company-news
              label: Company news
            - value: insights
              label: Industry insight
            - value: press
              label: Press release
            - value: product
              label: Product update
      - name: author
        label: Author
        type: select
        required: false
        options:
          creatable: true
          multiple: false
          values:
            - Emma Grönlund
            - Ilkka Pirttimaa
            - Jussi Toivonen
            - Mathias Lindholm
            - Tomi Grönlund
        description: No author will be displayed in the article if this field is left empty.
      - name: authorDetails
        label: Author details
        type: reference
        required: false
        options:
          collection: authors
          value: '{name}'
          label: '{fields.name}'
          multiple: false
        description: If an author detail is selected, an 'about the author' section will be shown after the article.
      - name: cover
        label: Cover image
        type: image
        description: Used in listings and for link previews. To show it on the article page, add it separately in the Body field. Use a 16:9 aspect ratio and keep the image under 1 MB.
        required: true
        options:
          media: article_images
      - name: coverAlt
        label: Cover image alt text
        type: string
        description: A textual description of the cover image for accessibility and search engines.
        required: true
      - name: draft
        label: Draft
        type: boolean
        description: Draft articles are not visible to the public.
        default: true
      - name: callout
        label: Case example callout (optional)
        type: object
        required: false
        fields:
          - name: company
            label: Company
            type: select
            required: true
            options:
              creatable: true
              multiple: false
              values:
                - 'Areim'
                - 'Avant'
                - 'Conficap'
                - 'Lifeline'
                - 'LähiTapiola'
                - 'Patria'
                - 'Skanska'
                - 'SRV'
                - 'Varte'
            description: No logo will be shown if the vector file is not found in `/src/assets`.
          - name: value
            label: Result value
            type: string
            required: true
            description: The result value, e.g. '50k+'.
          - name: label
            label: Result label
            type: string
            required: true
            description: The result label, e.g. 'Data points'.
      - name: body
        label: Body
        type: rich-text
        options:
          media: article_images
  - name: authors
    label: Authors
    type: collection
    path: src/content/authors
    filename: '{primary}.yml'
    subfolders: false
    view:
      primary: name
      fields: [image, name, title]
    fields:
      - name: image
        label: Image
        type: image
        required: true
        options:
          media: author_images
        description: Use a 1:1 aspect ratio and keep the image under 1 MB.
      - name: name
        label: Name
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: bio
        label: Bio
        type: text
        required: true
        pattern: { message: 'No line breaks allowed', regex: '^[^\r\n]*$' }
  - name: privacy-policy
    label: Privacy policy
    type: file
    path: src/pages/privacy-policy.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        description: Used for link previews/search results.
        required: true
        pattern: { message: 'No line breaks allowed', regex: '^[^\r\n]*$' }
      - name: body
        label: Body
        type: rich-text
  - name: information-security-practices
    label: Information security practices
    type: file
    path: src/pages/information-security-practices.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        description: Used for link previews/search results.
        required: true
        pattern: { message: 'No line breaks allowed', regex: '^[^\r\n]*$' }
      - name: body
        label: Body
        type: rich-text
  - name: general-terms-conditions
    label: General terms and conditions
    type: file
    path: src/pages/general-terms-and-conditions.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
        pattern: { message: 'No line breaks allowed', regex: '^[^\r\n]*$' }
      - name: body
        label: Body
        type: rich-text
  - name: site-settings
    label: Site settings
    type: file
    path: src/data/config.yml
    format: yaml
    fields:
      - name: title
        label: Site title
        type: string
        description: Used in browser tabs, link previews, and search results. On sub-pages, the title is added as a suffix, for example "News · Clouder".
        required: true
      - name: ogtitle
        label: Homepage link preview title
        type: string
        description: All other pages will use the "<page title> · <site title>" format.
        required: true
      - name: description
        label: Site description
        type: text
        description: Used for link previews/search results. Individual pages can override this with their own descriptions.
        required: true
        pattern: { message: 'No line breaks allowed', regex: '^[^\r\n]*$' }
settings:
  hide: true
  content:
    merge: true
