media:
  input: src/content/news/images
  output: ./images
content:
  - name: News
    type: collection
    path: src/content/news
    filename: '{primary}.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: featured
        label: Featured on the home page
        type: boolean
        default: false
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: cover
        label: Cover image
        description: The cover image will appear on listing pages and as the preview image when shared. To display this image in your post content, you'll need to insert it separately in the editor.
        type: image
      - name: body
        label: Body
        type: rich-text
    view:
      fields: [cover, title, date, draft, featured]
  - name: privacy-policy-en
    label: Privacy Policy
    type: file
    path: src/pages/privacy-policy.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        type: string
        required: true
      - name: description
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: privacy-policy-fi
    label: Tietosuojakäytäntö
    type: file
    path: src/pages/tietosuojakaytanto.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        type: string
        required: true
      - name: description
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: site-settings
    label: Site settings
    type: file
    path: src/data/site.yml
    format: yaml
    fields:
      - name: title
        label: Site title
        type: string
        required: true
      - name: description
        label: Site description
        type: string
        required: true
      - name: social
        label: Social links
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: href
            label: Title
            type: string
