media:
  input: src/content/news/images
  output: images
  extensions: [jpg, jpeg, png, webp]
content:
  - name: News
    type: collection
    path: src/content/news
    filename: '{primary}.md'
    subfolders: false
    view:
      fields: [cover, title, date, draft, category]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        description: Keep the description brief and avoid line breaks.
        required: true
        options:
          rows: 2
      - name: date
        label: Date
        type: date
        required: true
      - name: category
        label: Category
        type: select
        required: true
        options:
          multiple: false
          creatable: false
          values: [case-example, company-news, general, press-release, product-updates]
      - name: cover
        label: Cover image
        description: Cover image appears only in listings and link previews. Add it to the Body field if you want it in the post. Keep images under 1 MB.
        required: true
        type: image
      - name: draft
        label: Draft
        type: boolean
        description: Draft posts are not visible to the public.
        default: true
      - name: body
        label: Body
        type: rich-text
  - name: privacy-policy-en
    label: Privacy policy
    type: file
    path: src/pages/privacy-policy.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        description: Used in search results and link previews. Keep it brief and avoid line breaks.
        type: text
        required: true
        options:
          rows: 2
      - name: body
        label: Body
        type: rich-text
  - name: privacy-policy-fi
    label: Tietosuojakäytäntö
    type: file
    path: src/pages/tietosuojakaytanto.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        description: Used in search results and link previews. Keep it brief and avoid line breaks.
        type: text
        required: true
        options:
          rows: 2
      - name: body
        label: Body
        type: rich-text
  - name: site-settings
    label: Site settings
    type: file
    path: src/data/site.yml
    icon: file-cog
    format: yaml
    fields:
      - name: title
        label: Site title
        description: Used in browser tabs, search results, link previews and site footer. On sub-pages, the title is added as a suffix (e.g., "News · Clouder").
        type: string
        required: true
      - name: ogtitle
        label: Homepage link preview title
        description: Only applicable to the home page, all other pages will use the "<page title> · <site title>" pattern.
        type: string
        required: true
      - name: description
        label: Site description
        description: Used in search results and link previews. Individual pages can override this with their own descriptions. Keep it brief and avoid line breaks.
        type: text
        required: true
        options:
          rows: 2
      - name: social
        label: Social links
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^https?
            required: true
  - name: navigation
    label: Navigation
    type: file
    path: src/data/navigation.yml
    icon: file-cog
    format: yaml
    fields:
      - name: home
        label: Home
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: product
        label: Product
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: news
        label: News
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: contact
        label: Contact
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: privacy
        label: Privacy policy
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: guide
        label: Design guide
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: dashboard
        label: Dashboard
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
settings:
  hide: true
  content:
    merge: true
