media:
  input: src/content/news/images
  output: images
  categories: [image]
content:
  - name: News
    type: collection
    path: src/content/news
    filename: '{primary}.md'
    subfolders: false
    view:
      fields: [cover, title, date, draft, featured]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        description: Used in listing pages, search results and link previews. Keep it brief and avoid line breaks.
        required: true
        options:
          autoresize: false
          rows: 2
      - name: date
        label: Date
        type: date
        required: true
      - name: cover
        label: Cover image
        description: Please keep images under 1MB. Used in listing pages, search results and link previews. To display this image in your post content, you'll need to insert it separately in the editor.
        type: image
      - name: featured
        label: Featured
        type: boolean
        description: Two latest featured posts are shown on the home page. If no posts are featured, the section will be hidden.
        default: false
      - name: draft
        label: Draft
        type: boolean
        description: Draft posts are not visible to the public.
        default: true
      - name: body
        label: Body
        type: rich-text
  - name: privacy-policy-en
    label: Privacy policy
    type: file
    path: src/pages/privacy-policy.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: privacy-policy-fi
    label: Tietosuojakäytäntö
    type: file
    path: src/pages/tietosuojakaytanto.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: site-settings
    label: Site settings
    type: file
    path: src/data/site.yml
    icon: file-cog
    format: yaml
    fields:
      - name: title
        label: Site title
        description: Used in browser tabs, search results, link previews and site footer. On sub-pages, the title is added as a suffix (e.g., "News · Clouder").
        type: string
        required: true
      - name: description
        label: Site description
        description: Used in search results and link previews. Individual pages can override this with their own descriptions. Keep it brief and avoid line breaks.
        type: text
        required: true
        options:
          autoresize: false
          rows: 2
      - name: social
        label: Social links
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^https?
            required: true
  - name: navigation
    label: Navigation
    type: file
    path: src/data/navigation.yml
    icon: file-cog
    format: yaml
    fields:
      - name: home
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: product
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: news
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: contact
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: privacy
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: guide
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: dashboard
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
