media:
  input: src/content/news/images
  output: images
  categories: [image]
content:
  - name: News
    type: collection
    path: src/content/news
    filename: '{primary}.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: cover
        label: Cover image
        description: Please keep images under 1MB. The cover image will appear on listing pages and in social shares. To display this image in your post content, you'll need to insert it separately in the editor.
        type: image
      - name: featured
        label: Featured
        type: boolean
        description: Two latest featured posts are shown on the home page. If no posts are featured, the section will be hidden.
        default: false
        required: false
      - name: draft
        label: Draft
        type: boolean
        default: true
        required: false
      - name: body
        label: Body
        type: rich-text
    view:
      fields: [cover, title, date, draft, featured]
  - name: privacy-policy-en
    label: Privacy Policy
    type: file
    path: src/pages/privacy-policy.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        type: string
        required: true
      - name: description
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: privacy-policy-fi
    label: Tietosuojakäytäntö
    type: file
    path: src/pages/tietosuojakaytanto.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        type: string
        required: true
      - name: description
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: site-settings
    label: Site settings
    type: file
    path: src/data/site.yml
    format: yaml
    fields:
      - name: title
        label: Site title
        description: Appears in browser tabs, search results, social shares and site footer. On sub-pages, it's added as a suffix (e.g., "News · Clouder").
        type: string
        required: true
      - name: description
        label: Site description
        description: Default text shown in search results and social previews. Individual pages can override this with their own descriptions.
        type: string
        required: true
      - name: social
        label: Social links
        description: Add and manage social media links.
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: href
            label: URL
            type: string
            pattern: ^https?
  - name: navigation
    label: Navigation
    type: file
    path: src/data/navigation.yml
    format: yaml
    fields:
      - name: items
        label: Navigation Items
        description: Add and manage navigation items.
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
          - name: showInMainNav
            label: Show in main navigation
            type: boolean
            required: false
