media:
  input: src/content/news/images
  output: images
  extensions: [jpg, jpeg, png, webp]
content:
  - name: News
    type: collection
    path: src/content/news
    filename: '{primary}.md'
    subfolders: false
    view:
      fields: [cover, title, date, draft, category]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        description: Short description used for link previews and SEO.
        required: true
        pattern: { message: 'No line breaks allowed', regex: '^[^\r\n]*$' }
        options:
          rows: 2
      - name: date
        label: Date
        type: date
        required: true
      - name: category
        label: Category
        type: select
        required: true
        options:
          creatable: false
          multiple: false
          values:
            - value: case-example
              label: Case example
            - value: company-news
              label: Company news
            - value: general
              label: General
            - value: press-release
              label: Press release
            - value: product-updates
              label: Product updates
      - name: author
        label: Author
        type: select
        required: false
        options:
          creatable: true
          multiple: false
          values:
            - Emma Grönlund
            - Ilkka Pirttimaa
            - Jussi Toivonen
            - Mathias Lindholm
            - Tomi Grönlund
        description: No author will be displayed in the article if this field is left empty.
      - name: cover
        label: Cover image
        type: image
        description: The cover image appears only in listings and link previews. To show it on the article page, add it separately in the Body field. Keep images under 1 MB.
        required: true
      - name: coverAlt
        label: Cover image alt text
        type: string
        description: Describe the cover image briefly but meaningfully. Used for accessibility and SEO.
        required: true
      - name: draft
        label: Draft
        type: boolean
        description: Draft articles are not visible to the public.
        default: true
      - name: body
        label: Body
        type: rich-text
  - name: privacy-policy-en
    label: Privacy policy
    type: file
    path: src/pages/privacy-policy.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        description: Short description used for link previews and SEO.
        required: true
        pattern: { message: 'No line breaks allowed', regex: '^[^\r\n]*$' }
        options:
          rows: 2
      - name: body
        label: Body
        type: rich-text
  - name: privacy-policy-fi
    label: Tietosuojakäytäntö
    type: file
    path: src/pages/tietosuojakaytanto.md
    fields:
      - name: layout
        type: string
        default: '@layouts/ProseLayout.astro'
        required: true
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        description: Short description used for link previews and SEO.
        required: true
        pattern: { message: 'No line breaks allowed', regex: '^[^\r\n]*$' }
        options:
          rows: 2
      - name: body
        label: Body
        type: rich-text
  - name: site-settings
    label: Site settings
    type: file
    path: src/data/site.yml
    format: yaml
    fields:
      - name: title
        label: Site title
        type: string
        description: Used in browser tabs, search results, link previews and site footer. On sub-pages, the title is added as a suffix (e.g., "News · Clouder").
        required: true
      - name: ogtitle
        label: Homepage link preview title
        type: string
        description: Only used for link previews of the homepage. All other pages will use the "<page title> · <site title>" format.
        required: true
      - name: description
        label: Site description
        type: text
        description: Used for link previews and SEO. Individual pages can override this with their own descriptions.
        required: true
        pattern: { message: 'No line breaks allowed', regex: '^[^\r\n]*$' }
        options:
          rows: 2
      - name: social
        label: Social links
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^https?
            required: true
  - name: navigation
    label: Navigation
    type: file
    path: src/data/navigation.yml
    format: yaml
    fields:
      - name: home
        label: Home
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            pattern: ^(\/|https?)
            required: true
      - name: product
        label: Product
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            required: true
            pattern: ^(\/|https?)
      - name: news
        label: News
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            required: true
            pattern: ^(\/|https?)
      - name: contact
        label: Contact
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            required: true
            pattern: ^(\/|https?)
      - name: privacy
        label: Privacy policy
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            required: true
            pattern: ^(\/|https?)
      - name: dashboard
        label: Dashboard
        type: object
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: href
            label: URL
            type: string
            required: true
            pattern: ^(\/|https?)
settings:
  hide: true
  content:
    merge: true
