permissions:
  contents: write

name: Optimize New Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  optimize-images:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Checkout feature branch (for PRs)
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}

      - name: Check TinyPNG API key
        run: |
          if [ -z "${{ secrets.TINYPNG_API_KEY }}" ]; then
            echo "Error: TINYPNG_API_KEY is not set"
            exit 1
          fi

      - name: Install TinyPNG CLI
        run: npm install -g tinypng-cli

      - name: Get new and modified images
        id: new-images
        run: |
          BASE_BRANCH="${{ github.base_ref || 'main' }}"
          git fetch origin $BASE_BRANCH
          # Get the list of new or modified image files, excluding deleted files
          git diff --name-status origin/$BASE_BRANCH...HEAD | grep -E '^[AM]\s+.*\.(png|jpe?g)$' | cut -f2 > new_images.txt || true
          echo "New images detected:"
          cat new_images.txt || echo "No new images found."
          # Set output for conditionally skipping push (comma-separated)
          echo "images-to-optimize=$(paste -sd, new_images.txt)" >> $GITHUB_OUTPUT

      - name: Optimize images
        if: steps.new-images.outputs.images-to-optimize != ''
        run: |
          if [ -s new_images.txt ]; then
            while IFS= read -r image; do
              echo "Optimizing $image..."
              if tinypng --key ${{ secrets.TINYPNG_API_KEY }} "$image" -o "$image"; then
                echo "✅ Successfully optimized $image"
              else
                echo "❌ Failed to optimize $image"
                exit 1
              fi
            done < new_images.txt
          else
            echo "No new images to optimize."
          fi

      - name: Commit and push changes
        if: steps.new-images.outputs.images-to-optimize != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🔧 Optimized new images [skip ci]" || exit 0
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          BRANCH="${{ github.head_ref || github.ref_name }}"
          git push origin HEAD:$BRANCH
